### ISSUE TITLE
Any plan to support ensemble formation?

### ISSUE THREAD

**Issue by koreyou** [pfnet/optuna#289]
This is a feature request.

When we are in the state of hyperparameter tuning, we usually form ensembles to further boost its performance. Do you plan to implement (semi-) automatic way to form ensembles?

**Comment by toshihikoyanase** [comment]
Thank you for your feature request.

We've understood that some users including Kagglers need features to help form ensembles using optimization results, and we'd like to implement such features in the future.

For the meanwhile, please obtain trials using `study.trials` or `study.trials_dataframe()` and find trials suitable for ensemble models manually. In addition to that, [this FAQ page](https://optuna.readthedocs.io/en/stable/faq.html#how-to-save-machine-learning-models-trained-in-objective-functions) may be useful to save/restore the models trained in trials.

If you already have your implementation, we will welcome your pull request.

**Comment by koreyou** [comment]
Thank you for the reference. I will look into that.
