### ISSUE TITLE
Complete full trial count regardless of pruned trials.

### ISSUE THREAD

**Issue by MannyKayy** [pfnet/optuna#293]
Related to this [discussion](https://github.com/pfnet/optuna/pull/286#discussion_r243869460)

> In the case of pruned trials, it is useful to offer an option to automatically re-run the failed trials so that the full trial count is achieved. i.e. chainermn_study.optimize(objective, n_trials=25, rerun_pruned=True) such that len(study.trials) == n_trials == n_trials + (rerun_trials - pruned_trials)

**Comment by sile** [comment]
Thank you for your proposal.
I think it is not too difficult to achieve this by utilizing existing Optuna API. For example,
```python
# Sequential Version
study = optuna.create_study()
complete_trials = 0
while complete_trials < 10:   # Run 10 complete trials
    study.optimize(objective, n_trials=1)
    complete_trials = len([t for t in study.trials if t.state == optuna.structs.TrialState.COMPLETE])
```

```python
# ChainerMN Version
comm = chainermn.create_communicator()
study = optuna.integration.ChainerMNStudy(optuna.Study(study_name, storage_url), comm)
complete_trials = 0
while complete_trials < 10:   # Run 10 complete trials
    study.optimize(objective, n_trials=1)
    complete_trials = len([t for t in study.trials if t.state == optuna.structs.TrialState.COMPLETE])
    complete_trials = comm.mpi_comm.bcast(complete_trials)
```

Adding an option like `rerun_pruned` to `study.optimize(..)` seems more convenient for this use case, and we might decide to do in the future.
However, for preventing API to be bloated, we would like to be prudent about adding arguments if handy alternative ways exist.

**Comment by MannyKayy** [comment]
@sile 👍  that makes sense. Thanks for the response.
