### ISSUE TITLE
Getting `datetime_start` during a trial

### ISSUE THREAD

**Issue by iwiwi** [pfnet/optuna#294]
In some use cases, it would be useful if we could obtain trial's beginning time (i.e., `datetime_start`) from a `Trial` object during a trial.

**Comment by sile** [comment]
Resolved by the following PRs:
- https://github.com/pfnet/optuna/pull/523
- https://github.com/pfnet/optuna/pull/528
- https://github.com/pfnet/optuna/pull/548
