### ISSUE TITLE
Visualization not working

### ISSUE THREAD

**Issue by djKooks** [pfnet/optuna#308]
Hello.
I faced on error when:
```python
import optuna

study = optuna.create_study()
...
optuna.visualization.plot_intermediate_values(study)
```
this shows:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-11-04cb7fde5fca> in <module>
----> 1 optuna.visualization.plot_intermediate_values(study)

AttributeError: module 'optuna' has no attribute 'visualization'
```
Do I have to do something for visualization?

**Comment by g-votte** [comment]
Hi. Thanks for reporting the issue.

Have you installed Optuna from master branch?

The visualization module has not been released yet in PyPi, but just in master branch. Thus, current pip installation may cause the error: `AttributeError: module 'optuna' has no attribute 'visualization'`.

**Comment by djKooks** [comment]
@g-votte okay thanks! I'm testing with pip pkg manager, so it was the reason.

**Comment by AlvinLXS** [comment]
hello，i have faced a similar problem, look like this:

D:\Anaconda\python.exe E:/pytorch_scratch/optuna_example.py
Traceback (most recent call last):
  File "E:/pytorch_scratch/optuna_example.py", line 16, in <module>
    study = optuna.create_study()
AttributeError: module 'optuna' has no attribute 'create_study'

an interesting phenomenon is that when I run this code in Jupyter, it works well, but this error occurred when I run this demo in Pycharm

**Comment by AlvinLXS** [comment]
> hello，i have faced a similar problem, look like this:
> 
> D:\Anaconda\python.exe E:/pytorch_scratch/optuna_example.py
> Traceback (most recent call last):
> File "E:/pytorch_scratch/optuna_example.py", line 16, in 
> study = optuna.create_study()
> AttributeError: module 'optuna' has no attribute 'create_study'
> 
> an interesting phenomenon is that when I run this code in Jupyter, it works well, but this error occurred when I run this demo in Pycharm

I have finished this problem, please check the name of the file. The reason i met the problem is that there is a file named ```optuna.py```.

**Comment by Chidu2000** [comment]
Traceback (most recent call last):
  File "/home/ubuntu/Downloads/Pensieve-DRL-Master-thesis/pensieve-pytorch/optuna.py", line 219, in <module>
    main()
  File "/home/ubuntu/Downloads/Pensieve-DRL-Master-thesis/pensieve-pytorch/optuna.py", line 206, in main
    study = optuna.create_study(direction='minimize')

AttributeError: module 'optuna' has no attribute 'create_study'

**Comment by nzw0301** [comment]
Rename your file name except for optuna or package names.

**Comment by AndyChinghaha** [comment]
> Traceback (most recent call last): File "/home/ubuntu/Downloads/Pensieve-DRL-Master-thesis/pensieve-pytorch/optuna.py", line 219, in main() File "/home/ubuntu/Downloads/Pensieve-DRL-Master-thesis/pensieve-pytorch/optuna.py", line 206, in main study = optuna.create_study(direction='minimize')
> 
> AttributeError: module 'optuna' has no attribute 'create_study'

hi I meet the same situation in jupyter notebook with Optuna version 3.6.1 and python version 3.7; may I know how did you solve this problem.
