### ISSUE TITLE
"Using TensorFlow backend." is shown when `import optuna`

### ISSUE THREAD

**Issue by tamuhey** [pfnet/optuna#312]
Thanks for great tool!
When import optuna, always the stdout "Using TensorFlow backend." is shown.
I think it is due to  [optuna/integration/keras.py](https://github.com/pfnet/optuna/blob/master/optuna/integration/keras.py) .
Is it possible not to display this stdout?

**Comment by g-votte** [comment]
Hi, thanks for your reporting the issue.

We’ve also noticed that `import optuna` is getting a bit noisy especially with optional packages and been considering to improve that.

**Comment by g-votte** [comment]
Closing the issue, as it has been fixed since Optuna 0.9.0 (see also #334). Please reopen if you still see a similar problem.
