### ISSUE TITLE
support GPU?

### ISSUE THREAD

**Issue by Jie-Yuan** [pfnet/optuna#313]

**Comment by sile** [comment]
Although I have not enough information about the intent of this issue, I guessed you might be curious about one of the followings:
- (a) Using GPU in objective functions to accelerate your ML library:
  - There is no limitation to use GPU for this purpose.
  - For instructions on how to use the GPU with the library you are using, please follow the documentation of the library.
  - cf. [How can I use two GPUs for evaluating two trials simultaneously?](https://optuna.readthedocs.io/en/stable/faq.html#how-can-i-use-two-gpus-for-evaluating-two-trials-simultaneously)
- (b) To accelerate Optuna's optimization speed by using GPU:
  - Optuna doesn't have computations that can be speeded up by GPU. 
  - Therefore, we aren't planning to use GPU for Optuna itself.

If your intent differs from the above, please let me know the detail.

**Comment by g-votte** [comment]
Closing the issue. Please reopen this if you still have any concern.
