### ISSUE TITLE
Correctly handling sampler calls for low == high cases

### ISSUE THREAD

**Issue by iwiwi** [pfnet/optuna#318]
* Source: https://twitter.com/kutachu/status/1095218870250463232
* Example: https://colab.research.google.com/drive/1yRvYCPT0nTc0tEDBljkoGupfOBabgTwZ#scrollTo=pm4BsrN33kph

I found that, when `low == high`, calling `suggest_uniform` raises an internal exception. I think it would be useful if Optuna can correctly handle such calls.

**Comment by kutachu** [comment]
Thank you for substitute.

My indication in accordance with example.
I think, this problem in optuna.samplers.tpe.sampler._sample_uniform function.

It use float in 'low' and 'high', but after that optuna.samplers.tpe.sampler._sample_from_gmm function use 'if low >= high'.
Optuna should be rounding, or multiplied by coefficient like optuna.samplers.tpe.sampler._sample_int function.

I'm not experts, I'm sorry If I wrong.

Thank you.

**Comment by Minyus** [comment]
Current version of Optuna apparently does not support the same value for low and high for trial.suggest_uniform(). I often want to do this to include the constant float value in the log.

As a workaround, it is possible to use trial.suggest_categorical like this:

`float(trial.suggest_categorical('foo', ['0.123']))`

**Comment by sile** [comment]
Resolved: https://github.com/pfnet/optuna/pull/384
