### ISSUE TITLE
how to make use of existent experimental results?

### ISSUE THREAD

**Issue by speedcell4** [pfnet/optuna#320]
Hi~ I want to search for the best hyper-parameters with optuna, but I don't want to start from scratch. cause I have already done some experiments by manually setting hyper-parameters and some of them got good results. so is that possible to write these hyper-parameter settings and their corresponding results to optuna storage? and then I start optuna to continue searching with the help of these already done experiments.

like, can I do something like `optuna import --path /some/existent/experiments/path`, and then `optuna study optimize`.

on the other hand, currently I think I have a workaround, that is I just set this manually set hyper-parameter as the only possible value for `suggest_*` functions, and these functions will write hyper-parameters to the storage. after this stage, I change `suggest_*` to a broad range which I want to search in and start optuna, is this workable?

like, if the word dimension is manually set to 100, then I use `trial.suggest_int("word_dim", 100, 101)` to store this setting.

**Comment by toshihikoyanase** [comment]
Hi @speedcell4,

Thank you for your interest in Optuna.
Currently, Optuna does not provide functions/methods to import existing experimental results, but we are investigating the best way to implement the trial-import feature.

Here, I want to share my current workaround to import existing results.
1) Please install Optuna from `injected-trial` branch:

https://github.com/pfnet/optuna/tree/injected-trial/optuna

2) Use `InjectedTrial.suggest_xxx` methods to save existing results. Please refer to the following example for further details:

https://gist.github.com/toshihikoyanase/c90209d0352a119b26e1be7f152dbf53

---

> on the other hand, currently I think I have a workaround

Thank you for sharing your approach.
I think it is workable if you do not use `suggest_categorical`. Currently, it does not accept dynamic value spaces.

Here's an example to change ranges of `suggest_xxx` to import externally suggested parameter values.

https://gist.github.com/toshihikoyanase/99f4119f226da4ad227cd6f381136c72

Please note that TPESampler may raise ValueError when we set `low==high` as reported in #318. I used RandomSampler to avoid the issue in the above example.

If you have any questions, please let me know.

**Comment by speedcell4** [comment]
Thank you so much, that really helps
