### ISSUE TITLE
Feature request: conda recipe

### ISSUE THREAD

**Issue by sdrobert** [pfnet/optuna#327]
Hello,

[Conda](https://conda.io/en/latest/) is a centralized repository for many libraries, open source or otherwise. I'd like to request that a conda package be made for this project.

Thanks very much for your time,
Sean

**Comment by g-votte** [comment]
@sdrobert 
Thanks for your feedback! 

We agree that providing a conda package would make Optuna more accessible from many ML/DS projects, and will think it over.

**Comment by sdrobert** [comment]
@g-votte Thanks for your consideration :)

**Comment by sile** [comment]
I'm sorry to have kept you waiting, but Optuna is now available on conda-forge: https://github.com/conda-forge/optuna-feedstock
