### ISSUE TITLE
Description of Algorithm

### ISSUE THREAD

**Issue by yoriyuki** [pfnet/optuna#333]
Hi, 
We are using optuna for a research.  Could you describe the algorithm or better, show us a reference to a paper?  We know you are using Bayesian optimization but IIRC there are many methods which fall under the term of Bayesian.

**Comment by toshihikoyanase** [comment]
Hi @yoriyuki,

Thank you for using Optuna!
Optuna uses Tree-structured Parzen Estimator (TPE) as a default sampling algorithm. Please take a look at the following paper for further details of TPE.

James S. Bergstra, Rémi Bardenet,  Yoshua Bengio, Balázs Kégl: [Algorithms for Hyper-Parameter Optimization](https://papers.nips.cc/paper/4443-algorithms-for-hyper-parameter-optimization), in Proceedings of Advances in Neural Information Processing Systems 24 (NIPS 2011), [BibTeX](https://papers.nips.cc/paper/4443-algorithms-for-hyper-parameter-optimization/bibtex)
