### ISSUE TITLE
Add CatBoost example.

### ISSUE THREAD

**Issue by toshihikoyanase** [pfnet/optuna#352]
Add an example code of [CatBoost](https://github.com/catboost/catboost) under `examples/`.

**Comment by nmasahiro** [comment]
Can I work on this issue ?

**Comment by g-votte** [comment]
@nmasahiro 
Please go for it.

**Comment by scouvreur** [comment]
Hi @g-votte - can I work on this issue if it has been stalled ?

**Comment by g-votte** [comment]
@scouvreur 
Sure!

**Comment by sile** [comment]
Merged: https://github.com/pfnet/optuna/pull/477
