### ISSUE TITLE
Add `KerasPruningCallback` example.

### ISSUE THREAD

**Issue by g-votte** [pfnet/optuna#354]
Add a Keras example code with [`KerasPruningCallback`](https://github.com/pfnet/optuna/blob/master/optuna/integration/keras.py#L20) under `examples/pruning`.

**Comment by Rishav1** [comment]
I'm gonna take this up, if okay.

**Comment by sile** [comment]
OK!

**Comment by sile** [comment]
Merged: https://github.com/pfnet/optuna/pull/364
