### ISSUE TITLE
Rewrite numerical formulas in documentation by using MathJax.

### ISSUE THREAD

**Issue by sile** [pfnet/optuna#355]
To improve readability, we would like to rewrite numerical formulas in documentation by using MathJax.

**Comment by crcrpar** [comment]
Would you mind working on this?

**Comment by g-votte** [comment]
@crcrpar Please go for it!

**Comment by crcrpar** [comment]
I'm working on this and the current update is the below capture.

Is this OK for you?

Capture is a part of https://optuna.readthedocs.io/en/latest/reference/pruners.html.
- <img width="667" alt="image" src="https://user-images.githubusercontent.com/16191443/55144451-3c41f800-5184-11e9-9365-c9f8c9d76341.png">
- <img width="662" alt="image" src="https://user-images.githubusercontent.com/16191443/55144397-1caacf80-5184-11e9-9807-c947ab6d8200.png">
