### ISSUE TITLE
Add pruning callback for MXNet.

### ISSUE THREAD

**Issue by toshihikoyanase** [pfnet/optuna#356]
Add a callback function of MXNet to prune trials. Please refer to [this tutorial](https://mxnet.incubator.apache.org/versions/master/tutorials/r/CallbackFunction.html) about the callback mechanism of MXNet.

**Comment by Rishav1** [comment]
I would like to pick this up.

**Comment by g-votte** [comment]
@Rishav1 
Thanks! Please go for it.

**Comment by sile** [comment]
Merged: https://github.com/pfnet/optuna/pull/363
