### ISSUE TITLE
Suggested design changes.

### ISSUE THREAD

**Issue by Rishav1** [pfnet/optuna#368]
I think these changes would eventually come up anyways, so here are my suggestions on that.

- Add optional abstract callback function in BaseSampler and BasePruner, which is triggered for each trial on execution of trial.report(), supplying the trial_id and reported score.

- Add functionality for shared user variables across trials. The current storage.get/set_user_attr expects a trial_id. There should be additional functions to access serialized user_attr (perhaps based on trial_id or report timestamp) so that finding moving averages or last-k of user_attr is simple.

- A really cool feature for the CLI to have would be to directly input an executable and a list of tunable command line arguments that the executable supports (along with the range), and wrap the executable as an optuna objective (a trial's result can be identified using a supplied regex to look for in the executable's output). 
e.g. Let's say there is train_nn.py, that accepts arguments like --num_layers, --hiddens, --lr, --optimizer. Then running something like

```bash
$ optuna study optimize train_nn.py --n-trials=100 --study $STUDY_NAME --storage sqlite:///example.db \
--params num_layers:suggest_int(1,3) hiddens:suggest_int(1, 128) \
lr:suggest_uniform(0.00001,0.001) optimizer:suggest_categorical('Adam', 'MomentumSGD') \
--regex "Accuracy: ([0-1]+(?:\.[0-9]+)?)"
```
to run the optimization directly would be amazingly convenient.

**Comment by Rishav1** [comment]
@sile What is your opinion on the suggestions?

**Comment by sile** [comment]
Thank you for your useful suggestions.

> Add optional abstract callback function in BaseSampler and BasePruner, which is triggered for each trial on execution of trial.report(), supplying the trial_id and reported score.

As mentioned in https://github.com/pfnet/optuna/issues/346, we are planning to expose new sampler/pruner interfaces in the near feature. I think the new interface will meet your needs.

For example, new `BaseSampler` will have additional methods named `before` and `after`.
`after` is triggered each time when a trial execution finished, and the method takes `FrozenTrial` (this contains trial_id and the reported score) as the argument.


> Add functionality for shared user variables across trials.

I think `BaseStorage.set_study_user_attr` and `BaseStorage.get_study_user_attrs` can be used for this purpose.


> There should be additional functions to access serialized user_attr (perhaps based on trial_id or report timestamp) so that finding moving averages or last-k of user_attr is simple.

To keep storage API simple, we basically recommend calling `BaseStorage.get_all_trials` method and applying necessary processing to the resulting trials in your sampler or pruner (instead of adding new methods to `BaseStorage`).


> A really cool feature for the CLI to have would be to directly input an executable and a list of tunable command line arguments ...

Yes, it's very cool! Coincidentally, we were discussing this feature last month.
The concrete syntax and interface are under consideration, but we would like to provide the feature to Optuna users.

**Comment by Rishav1** [comment]
> As mentioned in #346, we are planning to expose new sampler/pruner interfaces in the near feature. I think the new interface will meet your needs.

I wasn't aware of that. That should be really helpful in adding new pruners and samplers.

> To keep storage API simple, we basically recommend calling BaseStorage.get_all_trials method and applying necessary processing to the resulting trials in your sampler or pruner (instead of adding new methods to BaseStorage).

I think it would be better to compromise on simplicity a little in exchange of performance gains(via direct database queries instead of python post procrssing). Plus, having extra functions available for the user doesn't hurt in the very least.

> Yes, it's very cool! Coincidentally, we were discussing this feature last month.
The concrete syntax and interface are under consideration, but we would like to provide the feature to Optuna users.

That's amazing! If possible, I would definitely like to contribute to the design.

**Comment by g-votte** [comment]
@Rishav1 

> That's amazing! If possible, I would definitely like to contribute to the design.

We'll release our prototype soon. Your feedback would be quite helpful, then.

**Comment by sile** [comment]
@Rishav1 

> I think it would be better to compromise on simplicity a little in exchange of performance gains(via direct database queries instead of python post procrssing). 

If we find that the performance impact is severe and the method is beneficial for many users/developers, we will consider to implement it to the storage. However, it is hard to remove the method once implemented as a part of the public interface, so we think that it is better that you try it with individual samplers and pruners at first.

**Comment by sile** [comment]
FYI: https://github.com/pfnet/optuna/pull/375 (new sampler interface)
