### ISSUE TITLE
Do you have any plans to support another sampler (ex: GPEI-based Bayesian optimization).

### ISSUE THREAD

**Issue by c-bata** [pfnet/optuna#381]
Hello! Thanks for developing this awesome optimization library.

I have a question about Optuna's sampler interface. Optuna currently supports TPE and Random search, but I would like to use GPEI-based Bayesian optimization in Optuna. There are some difficulties to implement it on Define-by-Run interface because we couldn't get the search space of all parameters explicitly.

I have a plan to implement GPEI sampler in the unique approach. There are rooms for discussion, so I was going to implement GPEI sampler as a third party optuna sampler. But I think that Optuna developers might have a plan to support another sampler's methods because the sampler interface in #380 provides `define_relative_search_space` and `sample_relative` methods. Can I have your plans to support another sampler's methods?

**Comment by sile** [comment]
Thank you for your question.

> I was going to implement GPEI sampler as a third party optuna sampler.

Cool! It is very welcome.

>  I think that Optuna developers might have a plan to support another sampler's methods

Yes, you're right. The primary motivation of #380 is to make it easier to develop samplers like Gaussian Process. For instance, by using the new interface, we can implement GP based sampler as  follows (it uses [skopt.Optimizer](https://scikit-optimize.github.io/optimizer/index.html#skopt.optimizer.Optimizer) internally).

```python
import skopt

from optuna import distributions
from optuna.samplers import BaseSampler
from optuna.structs import FrozenTrial
from optuna.structs import TrialState


class SkoptSampler(BaseSampler):
    def __init__(self):
        # type: () -> None

        self.optimizer = None
        self.search_space = {}
        self.param_names = []
        self.told_trials = set()

    def sample_relative(self, trial, search_space):
        # type: (FrozenTrial, Dict[str, distributions.BaseDistribution]) -> Dict[str, float]

        if len(search_space) == 0:
            return {}

        # [1] Initialize optimizer.
        if len(self.search_space) == 0:
            self.search_space = search_space

            # Convert optuna's search space to skopt's one.
            dimensions = []
            for name, distribution in search_space.items():
                if isinstance(distribution, distributions.UniformDistribution):
                    dimensions.append((distribution.low, distribution.high))
                    self.param_names.append(name)
                elif isinstance(distribution, distributions.IntUniformDistribution):
                    dimensions.append((distribution.low, distribution.high))
                    self.param_names.append(name)
                elif isinstance(distribution, distributions.CategoricalDistribution):
                    dimensions.append(distribution.choices)
                    self.param_names.append(name)
                else:
                    # TODO: Support other distributions.
                    pass

            self.optimizer = skopt.Optimizer(dimensions, "GP")

        # TODO: Support search space change (e.g., re-create optimizer instance).
        assert self.search_space == search_space

        # [2] Tell previous results.
        for trial in self.study.trials:
            if trial.number in self.told_trials or trial.state != TrialState.COMPLETE:
                continue
            self.told_trials.add(trial.number)

            params = []
            for name in self.param_names:
                assert name in trial.params_in_internal_repr  # TODO: Add error handling.

                internal = trial.params_in_internal_repr[name]
                value = self.search_space[name].to_external_repr(internal)
                params.append(value)

            self.optimizer.tell(params, trial.value)  # TODO: Support 'maximize' direction.

        # [3] Ask next parameters.
        params = self.optimizer.ask()
        return dict((n, self.search_space[n].to_internal_repr(p)) for n, p in zip(self.param_names, params))
```

**Comment by c-bata** [comment]
Thanks for your reply!

Great 👍  I was going to use `sklearn.GaussianProcessRegressor` but I think skopt is good choice (Especially I like the implementation of `skopt.space` package. That's really cool).

I thought that `before_trial` hook point (may be added at PR #375) is useful to GPEI sampler. But it looks the implementation of sampler you pasted here is enough simple. It seems I need to read the implementation of #380 and skopt to discuss.

Thanks. I wanna discuss about GPEI sampler with you again. 

P.S. I put some comments at #380.

**Comment by sile** [comment]
Thank you for your review comments, and we are looking forward to receiving your further feedback.
