### ISSUE TITLE
How to pass  params out of the object ?

### ISSUE THREAD

**Issue by zwqjoy** [pfnet/optuna#403]
I need pass the param out of the object:
how can I do

![image](https://user-images.githubusercontent.com/12653212/58376327-42ddc780-7f9b-11e9-8a94-8f0a398824eb.png)

Because I want predefine the  params conf , but now I found the params can only define in the object

If use want to  pass conf from file or config name, the fun can get the conf out of the object.

**Comment by zwqjoy** [comment]
I want user can pass the trial_params from the main fun

**Comment by g-votte** [comment]
Hi,

If your goal is to predefine constants for a part of the search space, you can pass the constants as follows.

```python
import optuna

config = load_your_config()  # e.g., {'booster': 'dart'}

def objective(trial):
    params = {
        'silent': 1,
        'objective': 'binary:logistic',
        'booster': trial.suggest_categorical('booster', ['gbtree', 'gblinear', 'dart'])
                   if 'booster' not in config else config['booster'],
        'lambda': trial.suggest_loguniform('lambda', 1e-8, 1.0)
                  if 'lambda' not in config else config['lambda'],
        'alpha': trial.suggest_loguniform('alpha', 1e-8, 1.0)
                 if 'alpha' not in config else config['alpha']
    }
    score = run_your_experiment(params)
    return score

study = optuna.create_study()
study.optimize(objective, n_trials=10)
print(study.best_trial)
```

If you want to define the search space outside the objective function, Optuna currently does not support that style.

Please feel free to ask any additional questions.
