### ISSUE TITLE
Apply maximize direction to example scripts.

### ISSUE THREAD

**Issue by g-votte** [pfnet/optuna#406]
Apply `maximize` direction to example scripts. Even though Optuna supports `maximize` direction since v0.9.0, some example scripts still use `minimize` returning `1.0 - accuracy` in their objective functions, e.g., https://github.com/pfnet/optuna/blob/master/examples/xgboost_simple.py#L64

**Comment by nmasahiro** [comment]
Can I work on this issue ?

**Comment by g-votte** [comment]
@nmasahiro 
Sure!
