### ISSUE TITLE
[Feature Request] Stop study with custom definition

### ISSUE THREAD

**Issue by WestonLu** [pfnet/optuna#411]
Can Optuna stop the study when some custom conditions are reached?

For example, when the difference between the target value and the result is less than 0.1?
 Or accuracy>0.9?

**Comment by sile** [comment]
Thank you for your question.

You can write code like the following:
```python
def objective(trial):
    ...

def is_custom_condition_satisfied(best_value):
    ...
    
study = optuna.create_study()
while True:
    study.optimize(objective, n_trials=1)
    if is_custom_condition_satisfied(study.best_value):
        break
```

Please let me know if this way doesn't satisfy your requirement.
