### ISSUE TITLE
[Feature Request] Log some other metrics in database

### ISSUE THREAD

**Issue by WestonLu** [pfnet/optuna#412]
For example, f1 score is my target value, but I also want to check and persistent acc and recall score during the trail. 

Now it seems that optuna can set intermediate_value, but intermediate_value is the key component for pruning, so I cannot save other value as intermediate_value but the target.

**Comment by g-votte** [comment]
Hi,

You can put the metrics to the trial's `user_attrs` with `trial.set_user_attr(...)` as follows.

```python
def objective(trial: optuna.Trial):
    ...
    acc = ...  # calculate the model's acc
    trial.set_user_attr('acc', acc)
    ...

study = optuna.create_study()
study.optimize(objective, n_trials=...)

print(study.best_trial.user_attrs)  # {'acc': ...}
```

**Comment by g-votte** [comment]
Closing the issue. Please reopen if you still have the problem.
