### ISSUE TITLE
No way to delete study

### ISSUE THREAD

**Issue by millskyle** [pfnet/optuna#421]
Searching the documentation and API shows no way to delete a study, e.g. clear all results and start fresh.  Is this possible, say through `optuna.delete_study(study_name='...', storage='mysql...')`.

In the case of a local db file, it an easily be deleted, however using a remote mysql server seems to require deleting all records from the database.

**Comment by sile** [comment]
Sorry, Optuna does not currently provide study deletion API.
We want to implement it, but the detailed schedule has not been decided.
After #422 has been merged, adding the API seems easy (thanks to @c-bata).
Of course, if you (or others) are interested in implementing the API, contributions are very welcome!

**Comment by millskyle** [comment]
Thank-you for the reply.  I will look into it if I get a chance, but for now I suppose I will get by with incremental study names.

**Comment by c-bata** [comment]
Hi! I added the ORM-level ON DELETE cascade option at #422. If we just deletes study object by using SQLAlchemy, then all associated records (like trials, study_user_attributes, ...) will be deleted.

The delete_study method of storage module is like following.
https://github.com/c-bata/optuna/compare/set-cascade-settings...c-bata:delete-study?expand=1

The user-level API design needs more consideration. It might be enough if Study class provides `delete` method. And perhaps, it might be useful if CLI provides the `delete-study` subcommand.
