### ISSUE TITLE
Support of custom driver connection configuration parameters to SQLAlchemy 

### ISSUE THREAD

**Issue by archenroot** [pfnet/optuna#423]
create_study, load_study methods (and others) should in case of using RDBMS backend like postgres/mysql support pass in additional parameters for connection making.

It seems like pool_size cannot be passed in SQL alchemy via DB url string like key value, SQLAlchemy fails on non recognized option.

So we need to let pass connection parameters to driver somehow to by passed to:
```
engine = create_engine('postgresql://me@localhost/mydb',
                       pool_size=my_pool_size, max_overflow=my_max_overflow)
```
So the load_study method can be extended like this (just dummy proposal):

Parameters: 

> study_name – Study’s name. Each study has a unique name as an identifier.
> storage – Database URL such as sqlite:///example.db. Optuna internally uses SQLAlchemy to handle 
> databases. Please refer to SQLAlchemy’s document for further details.
> **storage_configuration - Dictionary (K,V) to pass any kind of specific db driver supported parameters**
> sampler – A sampler object that implements background algorithm for value suggestion. If None is specified, TPESampler is used as the default. See also samplers.
> pruner – A pruner object that decides early stopping of unpromising trials. If None is specified, MedianPruner is used as the default. See also pruners.

Refer to: https://docs.sqlalchemy.org/en/13/core/engines.html#engine-creation-api

Ref: https://github.com/sqlalchemy/sqlalchemy/issues/4714

**Comment by archenroot** [comment]
What led me to this is that I use optuna with parallel jobs se to 4, but when on server where I have 64 cores I set jobs to 64, sqlite failing on locked db as it is not designed for concurrent access.

**Comment by sile** [comment]
Thank you for using Optuna.

As you mentioned, the current Optuna doesn't provide the way for specifying options of `create_engine` function.
We want to realize it by exposing [`RDBStorage`] to users. For example, after merging https://github.com/pfnet/optuna/pull/425, you can specify the custom options as follows:
```python
import optuna

options = {'pool_size'=my_pool_size, 'max_overflow'=my_max_overflow}
storage = optuna.storages.RDBStorage('postgresql://me@localhost/mydb', engine_kwargs=options)

study = optuna.create_study(study_name='foo', storage=storage)
```

Note that the public methods of [`RDBStorage`] except the construct are not intended to be used by users. We're planning to make those methods private in the future.

[`RDBStorage`]: https://github.com/pfnet/optuna/blob/f58a02736751deee6798a111d8b9b8d3a8b038a1/optuna/storages/rdb/storage.py#L37

**Comment by archenroot** [comment]
@sile - ok, I saw its merged, I will test it :-)
