### ISSUE TITLE
Add Keras example.

### ISSUE THREAD

**Issue by sile** [pfnet/optuna#458]
Add a Keras example code under `examples/`.

**Comment by Minyus** [comment]
I developed a Python package designed to optimize hyperparameters of Keras Deep Learning models using Optuna: 

https://github.com/Minyus/optkeras

Supported features include pruning, logging, and saving models.

You can run the demo in Google Colab:

https://colab.research.google.com/github/Minyus/optkeras/blob/master/examples/OptKeras_Example.ipynb

It might be helpful to add a Keras example to Optuna.

**Comment by sile** [comment]
@Minyus It seems useful. Thank you for your information!

**Comment by scouvreur** [comment]
Hi @sile is there anyone working on this ? Could I give a hand and open a PR ?

**Comment by sile** [comment]
@scouvreur 

>  Could I give a hand and open a PR ?

Of course. Please go for it!

**Comment by sile** [comment]
Merged: https://github.com/pfnet/optuna/pull/489
