### ISSUE TITLE
Is there something plan to replace trial.study with an InTrialStudy object?

### ISSUE THREAD

**Issue by c-bata** [pfnet/optuna#486]
InTrialStudy is added at https://github.com/pfnet/optuna/pull/380 for the new sampler interface. The docstring is below:

https://github.com/pfnet/optuna/blob/d3bc99f302ee3fead95697dd8da2cc0224619b56/optuna/study.py#L468-L482

From this comment, I expected `trial.study` is replaced with InTrialStudy class object. But the current implementation is not. Is there something plan to replace `trial.study` with the object of `InTrialStudy` ? (Or could you tell me if I misunderstood the purpose of InTrialStudy object?).

I've implemented InTrialStudy class in Goptuna at https://github.com/c-bata/goptuna/pull/42/commits/c1dab49b9a01bff1c601938d3080aa180aabe45e, and I noticed the current definition of InTrialStudy lacks `sampler` and `pruner` (for `trial.suggest_xxx` and `shoud_prune` methods).

<details>

Set a breakpoint inside an objective function.

```diff
(venv) $ git diff
diff --git a/examples/sklearn_simple.py b/examples/sklearn_simple.py
index 8f7f626..a679569 100644
--- a/examples/sklearn_simple.py
+++ b/examples/sklearn_simple.py
@@ -30,6 +30,8 @@ def objective(trial):
     iris = sklearn.datasets.load_iris()
     x, y = iris.data, iris.target
 
+    breakpoint()
+
     classifier_name = trial.suggest_categorical('classifier', ['SVC', 'RandomForest'])
     if classifier_name == 'SVC':
         svc_c = trial.suggest_loguniform('svc_c', 1e-10, 1e10)
```

Then check the `trial.study` object like:

```
(venv) $ python examples/sklearn_simple.py 
> /Users/a14737/src/github.com/pfnet/optuna/examples/sklearn_simple.py(35)objective()
     34 
---> 35     classifier_name = trial.suggest_categorical('classifier', ['SVC', 'RandomForest'])
     36     if classifier_name == 'SVC':

ipdb> p trial                                                                                                                                             
<optuna.trial.Trial object at 0x12ca939b0>
ipdb> p trial.study                                                                                                                                       
<optuna.study.Study object at 0x109678f60>
ipdb> p trial.study.optimize                                                                                                                              
<bound method Study.optimize of <optuna.study.Study object at 0x109678f60>>
ipdb>        
```

</details>

**Comment by sile** [comment]
Thank you for your question.
As you mentioned, we introduced `InTrialStudy` by #380 , but, after all, it turned out it's not so useful. We're going to remove `InTrialStudy` at #491 and add some runtime checks to prevent inappropriate use of `Study` object instead.

**Comment by c-bata** [comment]
Hi @sile!
I agree your opinion. I decide to close the PR which adds InTrialStudy to Goptuna.
Thank you!
