### ISSUE TITLE
Pruning callback for tf.keras

### ISSUE THREAD

**Issue by sfujiwara** [pfnet/optuna#490]
**Conditions**
- Optuna version: 0.14.0
- Python version: 3.6.8
- OS: Colaboratory
- Machine Learning library to be optimized: TensorFlow 2.0.0-beta1

**Error messages, stack traces, or logs**

```
AttributeError: 'KerasPruningCallback' object has no attribute 'on_train_batch_begin'
...
```

**Problem**

Callback for tf.keras requires to implement `on_train_batch_begin` method (and other methods):
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/callbacks/Callback#on_train_batch_begin

while original Keras does not:
https://keras.io/ja/callbacks/

To use callback for pruning with tf.keras, we need to modify `KerasPruningCallback` to keep compatibility or implement a new callback for tf.keras.

**Comment by hiro-o918** [comment]
I have also met this problem.
Temporarily, we can avoid this error by using the blow MixIin class.


```
from optuna.integration import KerasPruningCallback

class CallbackV2Mixin(object):
    def on_train_batch_begin(self, batch, logs=None):
        self.on_batch_begin(batch, logs=logs)

    def on_train_batch_end(self, batch, logs=None):
        self.on_batch_end(batch, logs=logs)

    def on_test_batch_begin(self, batch, logs=None):
        pass

    def on_test_batch_end(self, batch, logs=None):
        pass

    def on_predict_batch_begin(self, batch, logs=None):
        pass

    def on_predict_batch_end(self, batch, logs=None):
        pass

    def on_train_begin(self, logs=None):
        pass

    def on_train_end(self, logs=None):
        pass

    def on_test_begin(self, logs=None):
        pass

    def on_test_end(self, logs=None):
        pass

    def on_predict_begin(self, logs=None):
        pass

    def on_predict_end(self, logs=None):
        pass

class KerasPruningCallbackV2(CallbackV2Mixin, KerasPruningCallback):
    pass
```

**Comment by toshihikoyanase** [comment]
Hi @sfujiwara,

We're also thinking of the design of the pruning callback for TensorFlow 2.0. Actually, we received an issue related to the pruning callback for `tf.keras` and I created a prototype of the new callback [`TFKerasCallback`](https://github.com/pfnet/optuna/issues/471#issuecomment-519359283) as a workaround. I chose this approach because the internal implementation of `tf.keras` is getting different from the original `keras` according to your talk at the TSUBAME hackathon.

Can we discuss this issue in details at the PyCon JP Sprint?

Hi @hiro-o918,

Thank you for sharing your workaround. I also created a callback for `tf.keras`, and let me share it just for your information.

```python
from tensorflow.keras.callbacks import Callback

class TFKerasPruningCallback(Callback):

    def __init__(self, trial, monitor):
        # type: (optuna.trial.Trial, str) -> None

        super(TFKerasPruningCallback, self).__init__()

        self.trial = trial
        self.monitor = monitor

    def on_epoch_end(self, epoch, logs=None):
        # type: (int, Dict[str, float]) -> None

        logs = logs or {}
        current_score = logs.get(self.monitor)
        if current_score is None:
            return
        self.trial.report(current_score, step=epoch)
        if self.trial.should_prune():
            message = "Trial was pruned at epoch {}.".format(epoch)
            raise optuna.structs.TrialPruned(message)
```

**Comment by sile** [comment]
Merged https://github.com/pfnet/optuna/pull/530
