### ISSUE TITLE
Suggest the use of Decimal in _adjust_discrete_uniform_high

### ISSUE THREAD

**Issue by A03ki** [pfnet/optuna#503]
When, for instance, [suggest_discrete_uniform](https://github.com/pfnet/optuna/blob/master/optuna/trial.py#L223) is set by low=0.1, high=1.0 and q=0.1,  I predict that the range of parameter is [0, 1.0].  However, the range of parameter  is replaced by [0, 0.9].  It isn’t Intuitive. 

This issue is in [_adjust_discrete_uniform_high](https://github.com/pfnet/optuna/blob/master/optuna/trial.py#L700).

```
def _adjust_discrete_uniform_high(name, low, high, q):
    # type: (str, float, float, float) -> float

    r = high - low

    if math.fmod(r, q) != 0:
        high = (r // q) * q + low
        logger = logging.get_logger(__name__)
        logger.warning('The range of parameter `{}` is not divisible by `q`, and is '
                       'replaced by [{}, {}].'.format(name, low, high))

    return high
```

Example
```
import math

r = 1.0
q = 0.1
math.fmod(r, q) != 0  # True
```
This isn’t a zero. Therefore, I suggest the use of Decimal.

Example
```
import decimal

r = decimal.Decimal(str(1.0))
q = decimal.Decimal(str(0.1))
(r % q) != decimal.Decimal('0.0')  # False
```
This is a zero.

Do you have any thoughts?

**Comment by sile** [comment]
Thank you for your suggestion. 
We also think that the current behavior isn't intuitive.
The use of `decimal` module seems good. We would like to rewrite `_adjust_discrete_uniform_high` function by using `decimal`. Of course, PR is welcome if you're interested.

**Comment by A03ki** [comment]
I have a question about PR.
Should I separate PR for the enhanced function and this test or not?

Currently, an round-off error is the specification. Therefore, [range_config](https://github.com/pfnet/optuna/blob/master/tests/test_trial.py#L89) has to be corrected because the enhanced function can’t pass the test.

**Comment by sile** [comment]
I think that it's better to update both the function and related unit tests within the same PR.
