### ISSUE TITLE
Add Python3.4 version check to RDBStorage.

### ISSUE THREAD

**Issue by sile** [pfnet/optuna#516]
Because incompatible behavior of `namedtuple._asdict`, `RDBStorage` cannot work on Python3.4.
We want to add a check to detect the case at the head of `RDBStorage` constructor.

**Comment by c-bata** [comment]
This comment might be helpful.
https://github.com/pfnet/optuna/pull/520#issuecomment-531459060

**Comment by sile** [comment]
Merged: https://github.com/pfnet/optuna/pull/525
