### ISSUE TITLE
Ability to register a new best trial callback to the Study

### ISSUE THREAD

**Issue by daemonik** [pfnet/optuna#543]
For example

```python
def new_best(trial: Trial):
	print('optuna is awesome!')

study = optuna.create_study()
study.register_new_best_callback(new_best)
...
```
Obviously is is possible to poll the database for a new best, but this would make for a nice feature.

**Comment by toshihikoyanase** [comment]
Thank you for your feature request.
That is a part of our motivation to implement user-define callbacks of `study.optimize()` in this PR (https://github.com/pfnet/optuna/pull/480).
Using the callback feature, we can write such callback functions with a few lines of code as follows:

```python
def new_best_callback(study, trial):
    if study.best_trial.number == trial.number:
        print("Trial#{} marked the best score: {}.".format(trial.number, trial.value))

# ...

study = optuna.create_study()
study.optimize(objective, n_trials=10, callbacks=[new_best_callback])
```

Is it suitable for your use cases?

**Comment by daemonik** [comment]
Perfect!

Many Thanks.

**Comment by toshihikoyanase** [comment]
Let me close the issue. Please re-open if you have further questions or comments.
Thanks.
