### ISSUE TITLE
Chainer simple example should have pruning

### ISSUE THREAD

**Issue by Crissman** [pfnet/optuna#567]
Looked at Chainer example for Optuna, and noticed it was not using the Chainer Trainer extension for Pruning. I think that should be there.

**Comment by Crissman** [comment]
If ok, I'll make a PR to add it.

**Comment by sile** [comment]
Sounds good. Please go for it!

**Comment by sile** [comment]
Resolved by https://github.com/pfnet/optuna/pull/614.
