### ISSUE TITLE
tf.function-decorated function tried to create variables on non-first call

### ISSUE THREAD

**Issue by alexacgomes** [pfnet/optuna#572]
**Conditions**
- Optuna version: 0.16.0
- Python version: 3.7.3
- OS: Win 
- Machine Learning library to be optimized: Tensorflow 1.14.0

**Code to reproduce**

```
@tf.function
def learn(model, optimizer, state, reward, action=False, mode='train'):
    
    with tf.GradientTape() as tape:    
        logits = model(state, training=(mode=='train'))
        actions_one_hot = tf.one_hot(action, 2)
        neg_cross_entropy = tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits,labels=actions_one_hot)
        sharpe = _sharpe_ratio(reward)
        loss_value = tf.reduce_mean(tf.multiply(neg_cross_entropy, sharpe))
        grads = tape.gradient(loss_value, model.variables)
        optimizer.apply_gradients(zip(grads, model.variables))
```

**Error messages, stack traces, or logs**

```
 ValueError: tf.function-decorated function tried to create variables on non-first call.

```
When executing Optuna with the tf.function decorator, I get the error above.

Any ideas how to solve this?

Thank you.

**Comment by toshihikoyanase** [comment]
> Machine Learning library to be optimized: Tensorflow 1.14.0

IMO, the cause may be related to TensorFlow version because `tf.function` decorator has been officially introduced since 2.0.0. I created [a notebook](https://colab.research.google.com/drive/1F6cL6jZgkcM7D7rEfODESYIZUwusiQpM), and I checked the combination of `tf.function` and `Optuna` properly worked if I updated TensorFlow to `2.0.0`. 

If you still have problem, is it possible to share working examples? The current example needs some extra code which setups `model`, `optimizer` and etc.

**Comment by alexacgomes** [comment]
> 
> 
> > Machine Learning library to be optimized: Tensorflow 1.14.0
> 
> IMO, the cause may be related to TensorFlow version because `tf.function` decorator has been officially introduced since 2.0.0. I created [a notebook](https://colab.research.google.com/drive/1F6cL6jZgkcM7D7rEfODESYIZUwusiQpM), and I checked the combination of `tf.function` and `Optuna` properly worked if I updated TensorFlow to `2.0.0`.
> 
> If you still have problem, is it possible to share working examples? The current example needs some extra code which setups `model`, `optimizer` and etc.

I moved "def train" inside "def objective" as in the notebook you created and it worked it!

Thanks a lot!
