### ISSUE TITLE
Remove description of `Study.__init__` arguments.

### ISSUE THREAD

**Issue by toshihikoyanase** [pfnet/optuna#576]
The current documentation of the `Study` class explains the arguments `Study.__init__`. I think it may be misleading to be able to create `Study` instances directly. If we remove the description of the arguments, the guidance to `create_study` and `load_study` will be clear.

Please remove the following description from the `Study.__init__` reference:

![image](https://user-images.githubusercontent.com/3255979/66176321-3a5b7300-e698-11e9-9017-ebb6713b82dd.png)

The code corresponding to the reference:

https://github.com/pfnet/optuna/blob/ab88210e0f381206673637907c298a1973715553/optuna/study.py#L150-L166

**Comment by sile** [comment]
Merged: https://github.com/pfnet/optuna/pull/579
