### ISSUE TITLE
Dashboard only supports direction="minimize"

### ISSUE THREAD

**Issue by louisabraham** [pfnet/optuna#586]
![image](https://user-images.githubusercontent.com/13174805/66481128-821b3980-eaa0-11e9-835e-34f47db3c2a6.png)

I used `optuna create-study --direction maximize --storage sqlite:///example.db` to create my study but the curve on the dashboard tracks only the minimum, not the maximum.

Maybe this is an error of `create-study` that doesn't take my argument into account…

**Comment by c-bata** [comment]
Nice catch @louisabraham! I fixed this bug at #587.

**Comment by louisabraham** [comment]
Awesome support!
