### ISSUE TITLE
Contrast of slice plot is low.

### ISSUE THREAD

**Issue by toshihikoyanase** [pfnet/optuna#609]
The following image is an example of slice plots. The points highlighted by the red circles have similar colors to the background, and it is difficult for users to find such points. I think we can improve the readability of slice plots by changing the color scale and/or background color.

![slice-plot-low-contrast](https://user-images.githubusercontent.com/3255979/66909515-da75ac80-f047-11e9-94ca-3958ddf81c39.png)

## Code to reproduce

```python
import optuna

def objective(trial):
    x = trial.suggest_uniform('x', -10, 10)
    y = trial.suggest_uniform('y', -10, 10)
    return x - y

study = optuna.create_study()
study.optimize(objective, n_trials=20)

optuna.visualization.plot_slice(study)
```

## Library version

optuna: 0.17.1
plotly: 4.1.1

**Comment by sile** [comment]
Resolved: https://github.com/pfnet/optuna/pull/661
