### ISSUE TITLE
Will you be planning a conda-forge release?

### ISSUE THREAD

**Issue by ericmjl** [pfnet/optuna#647]
It's as per message. I'm interested in getting optuna into conda-forge, as it will keep my environment.yml clean. I'm happy to help with getting the recipe pushed up, if it helps you all :smile:. And if we go that route, please ping in here if you'd like to be a recipe maintainer; it's not difficult really, once we have the recipe merged in, it's mostly a matter of merging new version pull requests that a bot makes to the recipe.

**Comment by sile** [comment]
Thank you for your proposal!
We are just preparing to register Optuna to conda-forge, so please be patient for a while.

**Comment by sile** [comment]
Optuna is now available on conda-forge: https://github.com/conda-forge/optuna-feedstock
