### ISSUE TITLE
Add tags list in addition of study_name

### ISSUE THREAD

**Issue by arita37** [pfnet/optuna#664]
## Motivation
    For post analysis purpose, can you add 
    study(tags =[ "myporject1, "cat1", "cat2"])  when defining a study.

So, the logs are easier to analyze (instea of just studdy name comparison).

**Comment by toshihikoyanase** [comment]
Thank you for the feature request.
For that purpose, I think you can use user attributes of `Study` as follows:

```python
study = optuna.create_study()
study.set_user_attr('project_name', 'myproject1')
```

I created a notebook to show the basic usage of the user attributes.
Please take a look at it, and please let us know if you still have issues or requests.
https://colab.research.google.com/drive/1E14gAwPRl0p3auIC9oI5BWN_MZWh_KRE

**Comment by arita37** [comment]
Thanks.
How this is stored in  Database ?
A single column with string list of attributes.

By the way, thanks for Optuna, a very well designed project. This is rare to mention it ....

**Comment by toshihikoyanase** [comment]
Thank you for your kind words!

> How this is stored in  Database ?

`study_user_attributes` table manages attribute key-value pairs. The key is stored as a string while the value is serialized in JSON and stored as a string. The corresponding code is [here](https://github.com/pfnet/optuna/blob/master/optuna/storages/rdb/models.py#L87-L112). Please note that the key and the value have the maximum lengths ([512 and 2048](https://github.com/pfnet/optuna/blob/master/optuna/storages/rdb/models.py#L29-L30), respectively).

**Comment by arita37** [comment]
Thanks for it.
Key-value is best for tag type values.


1) Think having functional interface in front 
of class based is best for research oriented code.
Believe we should organize a meetup to explain
the value of functionnal type API (vs all OO)...


2) Another interesting point for optuna, is adding statistics properties of the input data (ie 
    mean, variance, skew, Mutual info) and 
meta-data ( dataset category....).

It would help for some kind of “meta-learning”
on hyperparameters.... although extensive studies is needed.

Thanks again

**Comment by toshihikoyanase** [comment]
>  a meetup to explain the value of functionnal type API

Thank you for your suggestion.
When we organize a meetup, I'll let you know.
Please share your idea at that time!


> adding statistics properties of the input data and meta-data

Does the input data mean the input of Machine Learning models like feature vectors?
If so, such a feature seems to be useful for feature engineering.
Currently, Optuna focuses on hyperparameter tuning, but supporting other parts of a Machine Learning pipeline is a possible future direction of Optuna (or Optuna's family software), IMO.


> “meta-learning” on hyperparameters

FYI: New visualization functions (e.g., [slice plot](https://nbviewer.jupyter.org/github/pfnet/optuna/blob/master/examples/visualization/plot_slice.ipynb)) provided by Optuna v0.18.0 also help meta-learning on hyperparameters. Please take a look at them!
https://optuna.readthedocs.io/en/stable/reference/visualization.html

**Comment by arita37** [comment]
Thanks for your remarks.

1) Making good API is hard


2) My view is 
( Dataset, Model)(i)—-> Optimal Hyper (i)

As we cannot store all the datasets,
we use the statistics for meta-learning :

Statistics( Dataset )—>  (mean, skew,...)

With the sample data ,
( Statistics(Dataset), Model )(i)  ,
creates a model to predict Hyper values
And re-use as “meta-learning”.

Example :
   If We take Cifar and some CNN models, 
   We may end up with similar hyperparamfers ...


Happy to discuss on this (!)

**Comment by toshihikoyanase** [comment]
Thank you for your explanation. I understood your idea in more detail.

It would be great if users can predict scores of hyperparameters by using the meta-feature.
I'm not familiar with this field, so I'm not sure about the feasibility of the meta-learning.
Please share research results (such as papers or OSS) if possible.

**Comment by arita37** [comment]
Hello,

There is this paper which relates the idea
https://arxiv.org/pdf/1911.02590.pdf

Mostly , NNweightS = F(hyper) based on
training data, test data.


Maybe, for images related data and Resnet,
the intuition is easier.

Given a NNet,  hyper = G(train data, test data)


Topic is kind of new.... so investigation is required !!!!

**Comment by arita37** [comment]
Some additional papers :

https://arxiv.org/abs/1712.06283

http://proceedings.mlr.press/v80/franceschi18a/franceschi18a.pdf


Think we can test on some synthetic dataset
and a simple NNetwork classifier.

This is a good topic for optuna (!)

Thanks

**Comment by toshihikoyanase** [comment]
Thank you for sending the papers. I’ll read them.

BTW, this issue was originally about the study-tag feature. I think it was already resolved, and let me close this issue. Please create another one to discuss meta-learning.

I personally feel that meta-learning is still in the research phase, and we need in-depth discussion before designing/creating software. So, I’d like to talk about it in the meet-up as well as the functional interface.

Anyway, let us discuss it in a new issue or a meet-up.

**Comment by arita37** [comment]
Thats makes sense.
Lets open a topic for this meta-learning.

Its still research phase.... But, good framework
may also help the researchers for investigation (!)

Lets talk at the meetup.

Thanks !
