### ISSUE TITLE
AttributeError: '_BaseIntUniformDistribution' object has no attribute 'to_internal_repr'

### ISSUE THREAD

**Issue by licsh** [pfnet/optuna#677]
Hi, first of all the project is very nice,  recently i have used optuna to help me to find the best performance parameters of the model  in my programs, the result is good  but i got some  error info like this:  
param_value = distribution.to_internal_repr(trial.params[param_name])
AttributeError: '_BaseIntUniformDistribution' object has no attribute 'to_internal_repr'
Setting status of trial#511 as TrialState.FAIL because of the following error: AttributeError("'_BaseIntUniformDistribution' object has no attribute 'to_internal_repr'")

I want to know why and what happend

**Comment by sile** [comment]
Thank you for reporting this problem.

Could you tell me more detailed log messages (stacktrace) or runnable Python code to reproduce this problem for further investigation?

BTW, It seems that the error is similar to https://github.com/pfnet/optuna/issues/571, so the answer to the issue may help you.

**Comment by licsh** [comment]
awsome!!!  the problem is same as what you paste, thank you very much

**Comment by sile** [comment]
Resolved by https://github.com/pfnet/optuna/pull/573.
