### ISSUE TITLE
Can't pass parameters to objective when using parallel (joblib)

### ISSUE THREAD

**Issue by eafpres** [pfnet/optuna#688]
Hi--the module is great.  Beautiful integration with the dB, ability to easily save any/all parameters etc.  I'm struggling as I would like to pass parameters to the objective function when called from a parallel optimization

```
def optimize(n_trials, study_name):
    study = (optuna.load_study(study_name = study_name,
                               storage  = 'sqlite:///' + study_name + '.db'))
    study.optimize(train_model, n_trials = n_trials, timeout = None)
```

In the above, I'd like to change the model reference, train_model, to include parameters, e.g:

```
study.optimize(train_model(par1, par2, ..., parn), n_trials = n_trials, timeout = None)
```
where train_model looks like:  

```
def train_model(trial):  
    x = trial.suggest_uniform('x', x_range[0], x_range[1])  
    y = trial.suggest_uniform('y', y_range[0], y_range[1])  
    return (x - 2) ** 2 - (y - 12) ** 3 + y
```

but when I try that, it complains about missing argument (trial) but if I try to add it, it reports trial doesn't exist.

**Comment by hvy** [comment]
Hi @eafpres and thank you for the kind words. Passing arbitrary arguments to the objective function is a rather common case and it's actually covered in the [FAQ in the documentation](https://optuna.readthedocs.io/en/latest/faq.html#how-to-define-objective-functions-that-have-own-arguments). Given that you are using `joblib` however, I wrote a [minimal working example](https://gist.github.com/hvy/86c7d33ebda94f5ad74169ba39a3b52d) which I think addresses your needs. Please let me know if I am missing your point.

**Comment by eafpres** [comment]
@hvy Thank you for your prompt and complete feedback.  Sorry I had missed the information in the FAQ!  I will follow your examples and revert with any questions.

**Comment by TyrionBian** [comment]
import optuna

# Objective function that takes three arguments.
def objective(trial, min_x, max_x):
    x = trial.suggest_float("x", min_x, max_x)
    return (x - 2) ** 2


# Extra arguments.
min_x = -100
max_x = 100

# Execute an optimization by using the above objective function wrapped by `lambda`.
study = optuna.create_study()
study.optimize(lambda trial: objective(trial, min_x, max_x), n_trials=100)
